name: komtim_partner
description: A new Flutter project.
publish_to: "none"

version: 1.2.9+0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  overlay_support: ^2.1.0
  firebase_core: ^2.17.0
  firebase_messaging: ^14.2.0
  firebase_analytics: ^10.6.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^12.0.1
  path_provider: ^2.1.1
  open_file: ^3.3.2
  google_fonts: ^8.1.0
  go_router: ^9.0.0
  get_it: ^7.6.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  provider: ^6.1.2
  shared_preferences: ^2.2.0
  connectivity_plus: ^4.0.1
  cached_network_image: ^3.3.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  webview_flutter: ^4.0.1
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.0.0
  flutter_secure_storage: ^8.0.0
  pinput: ^3.0.0
  lottie: ^2.6.0
  shimmer: ^3.0.0
  upgrader: ^9.0.0
  flutter_flavor: ^3.0.4
  logger: ^2.0.2+1
  qr_flutter: ^4.1.0
  flutter_countdown_timer: ^4.1.0
  fluttertoast: ^8.0.7
  device_info_plus: ^9.1.0
  dart_jsonwebtoken: ^2.2.0
  flutter_svg: ^2.0.9
  firebase_remote_config: ^4.3.14
  package_info_plus: ^4.2.0
  in_app_update: ^4.2.2
  dio: ^5.9.1
  app_links: ^6.3.3
  chucker_flutter: ^1.9.1
  widgetbook_annotation: ^3.11.0
  widgetbook: ^3.22.0
  recaptcha_enterprise_flutter: 18.8.1
  fl_chart: ^1.2.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.5.0
  widgetbook_generator: ^3.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/superapp/
    - assets/images/superapp/auth/
    - assets/images/superapp/home/
    - assets/images/superapp/home/navbar/
    - assets/images/superapp/setting/
    - assets/images/superapp/topup/
    - assets/json/
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Regular.ttf
