// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhOgBAZx5MnMTLPJavU6ebE_anYaUkla8',
    appId: '1:750513473331:android:f002d06f9f1e559750a046',
    messagingSenderId: '750513473331',
    projectId: 'deep-geography-255006',
    databaseURL: 'https://deep-geography-255006.firebaseio.com',
    storageBucket: 'deep-geography-255006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpr972SOSdvuY2TG4b3SPKHOU900Se_hk',
    appId: '1:750513473331:ios:5a14690f60b3d94550a046',
    messagingSenderId: '750513473331',
    projectId: 'deep-geography-255006',
    databaseURL: 'https://deep-geography-255006.firebaseio.com',
    storageBucket: 'deep-geography-255006.appspot.com',
    androidClientId:
        '750513473331-3nor20t1mgtp70kq905b6oum8q53c0ps.apps.googleusercontent.com',
    iosClientId:
        '750513473331-535at9jinamif6nm72g7h2m76ru738fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.komtimPartner',
  );
}
