// Mocks generated by Mockito 5.4.6 from annotations
// in komtim_partner/test/helpers/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i23;
import 'dart:ui' as _i37;

import 'package:dartz/dartz.dart' as _i13;
import 'package:dio/dio.dart' as _i4;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i6;
import 'package:komtim_partner/common/failure.dart' as _i28;
import 'package:komtim_partner/core/data/apiservice/dio_client.dart' as _i18;
import 'package:komtim_partner/core/data/apiservice/dio_response_parser.dart'
    as _i19;
import 'package:komtim_partner/core/data/apiservice/interceptors/auth_interceptor.dart'
    as _i3;
import 'package:komtim_partner/core/data/datasources/preferences/secure_storage_service.dart'
    as _i11;
import 'package:komtim_partner/core/data/datasources/preferences/shared_pref.dart'
    as _i2;
import 'package:komtim_partner/core/data/datasources/remote/auth_remote_datasource.dart'
    as _i24;
import 'package:komtim_partner/core/data/datasources/remote/invoice_remote_datasource.dart'
    as _i21;
import 'package:komtim_partner/core/data/models/check_email_response.dart'
    as _i8;
import 'package:komtim_partner/core/data/models/forget_pin_response.dart'
    as _i12;
import 'package:komtim_partner/core/data/models/invoice_detail_response.dart'
    as _i7;
import 'package:komtim_partner/core/data/models/invoices_response.dart' as _i22;
import 'package:komtim_partner/core/data/models/login_response.dart' as _i9;
import 'package:komtim_partner/core/data/models/profile_response.dart' as _i26;
import 'package:komtim_partner/core/data/models/talents_response.dart' as _i25;
import 'package:komtim_partner/core/domain/entities/attendance_model.dart'
    as _i36;
import 'package:komtim_partner/core/domain/entities/auth_state.dart' as _i14;
import 'package:komtim_partner/core/domain/entities/check_email_model.dart'
    as _i31;
import 'package:komtim_partner/core/domain/entities/invoice_detail_model.dart'
    as _i30;
import 'package:komtim_partner/core/domain/entities/invoices_model.dart'
    as _i29;
import 'package:komtim_partner/core/domain/entities/login_model.dart' as _i32;
import 'package:komtim_partner/core/domain/entities/profile_model.dart' as _i34;
import 'package:komtim_partner/core/domain/managers/authentication_manager.dart'
    as _i17;
import 'package:komtim_partner/core/domain/repositories/attendance_repository.dart'
    as _i35;
import 'package:komtim_partner/core/domain/repositories/auth_repository.dart'
    as _i15;
import 'package:komtim_partner/core/domain/repositories/invoice_repository.dart'
    as _i27;
import 'package:komtim_partner/core/domain/repositories/profile_repository.dart'
    as _i33;
import 'package:komtim_partner/core/domain/usecases/change_password_use_case.dart'
    as _i41;
import 'package:komtim_partner/core/domain/usecases/do_login_use_case.dart'
    as _i38;
import 'package:komtim_partner/core/domain/usecases/do_logout_use_case.dart'
    as _i39;
import 'package:komtim_partner/core/domain/usecases/get_profile_use_case.dart'
    as _i16;
import 'package:komtim_partner/core/domain/usecases/recaptcha_use_case.dart'
    as _i42;
import 'package:komtim_partner/core/domain/usecases/send_forgot_password_use_case.dart'
    as _i40;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i20;
import 'package:recaptcha_enterprise_flutter/recaptcha_action.dart' as _i43;
import 'package:shared_preferences/shared_preferences.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSharedPref_0 extends _i1.SmartFake implements _i2.SharedPref {
  _FakeSharedPref_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthInterceptor_1 extends _i1.SmartFake
    implements _i3.AuthInterceptor {
  _FakeAuthInterceptor_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_2 extends _i1.SmartFake implements _i4.Dio {
  _FakeDio_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3<T> extends _i1.SmartFake implements _i4.Response<T> {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_4<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSOptions_5 extends _i1.SmartFake implements _i6.IOSOptions {
  _FakeIOSOptions_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAndroidOptions_6 extends _i1.SmartFake
    implements _i6.AndroidOptions {
  _FakeAndroidOptions_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinuxOptions_7 extends _i1.SmartFake implements _i6.LinuxOptions {
  _FakeLinuxOptions_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWindowsOptions_8 extends _i1.SmartFake
    implements _i6.WindowsOptions {
  _FakeWindowsOptions_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebOptions_9 extends _i1.SmartFake implements _i6.WebOptions {
  _FakeWebOptions_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMacOsOptions_10 extends _i1.SmartFake implements _i6.MacOsOptions {
  _FakeMacOsOptions_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceDetailResponse_11 extends _i1.SmartFake
    implements _i7.InvoiceDetailResponse {
  _FakeInvoiceDetailResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCheckEvaluationResponse_12 extends _i1.SmartFake
    implements _i7.CheckEvaluationResponse {
  _FakeCheckEvaluationResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCheckEmailResponse_13 extends _i1.SmartFake
    implements _i8.CheckEmailResponse {
  _FakeCheckEmailResponse_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginResponse_14 extends _i1.SmartFake implements _i9.LoginResponse {
  _FakeLoginResponse_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_15 extends _i1.SmartFake
    implements _i10.SharedPreferences {
  _FakeSharedPreferences_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSecureStorageService_16 extends _i1.SmartFake
    implements _i11.SecureStorageService {
  _FakeSecureStorageService_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgetPinResponse_17 extends _i1.SmartFake
    implements _i12.ForgetPinResponse {
  _FakeForgetPinResponse_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_18<L, R> extends _i1.SmartFake implements _i13.Either<L, R> {
  _FakeEither_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthState_19 extends _i1.SmartFake implements _i14.AuthState {
  _FakeAuthState_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthRepository_20 extends _i1.SmartFake
    implements _i15.AuthRepository {
  _FakeAuthRepository_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetProfileUseCase_21 extends _i1.SmartFake
    implements _i16.GetProfileUseCase {
  _FakeGetProfileUseCase_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthenticationManager_22 extends _i1.SmartFake
    implements _i17.AuthenticationManager {
  _FakeAuthenticationManager_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i18.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPref get sharedPref => (super.noSuchMethod(
        Invocation.getter(#sharedPref),
        returnValue: _FakeSharedPref_0(
          this,
          Invocation.getter(#sharedPref),
        ),
      ) as _i2.SharedPref);

  @override
  _i3.AuthInterceptor get authInterceptor => (super.noSuchMethod(
        Invocation.getter(#authInterceptor),
        returnValue: _FakeAuthInterceptor_1(
          this,
          Invocation.getter(#authInterceptor),
        ),
      ) as _i3.AuthInterceptor);

  @override
  _i4.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_2(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i4.Dio);

  @override
  _i5.Future<_i4.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i5.Future<_i4.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response<dynamic>>);

  @override
  _i5.Future<_i4.Response<dynamic>> post(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i5.Future<_i4.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response<dynamic>>);

  @override
  _i5.Future<_i4.Response<dynamic>> put(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i5.Future<_i4.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response<dynamic>>);

  @override
  _i5.Future<_i4.Response<dynamic>> delete(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue:
            _i5.Future<_i4.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response<dynamic>>);

  @override
  _i5.Future<_i4.Response<dynamic>> patch(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i5.Future<_i4.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response<dynamic>>);
}

/// A class which mocks [DioResponseParser].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioResponseParser extends _i1.Mock implements _i19.DioResponseParser {
  MockDioResponseParser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  T parseResponse<T>(
    _i4.Response<dynamic>? response,
    T Function(dynamic)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseResponse,
          [
            response,
            fromJson,
          ],
        ),
        returnValue: _i20.dummyValue<T>(
          this,
          Invocation.method(
            #parseResponse,
            [
              response,
              fromJson,
            ],
          ),
        ),
      ) as T);

  @override
  T parseResponseMetaData<T>(
    _i4.Response<dynamic>? response,
    T Function(dynamic)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseResponseMetaData,
          [
            response,
            fromJson,
          ],
        ),
        returnValue: _i20.dummyValue<T>(
          this,
          Invocation.method(
            #parseResponseMetaData,
            [
              response,
              fromJson,
            ],
          ),
        ),
      ) as T);

  @override
  _i5.Future<T> parseResponseMeta<T>(
    _i4.Response<dynamic>? response,
    T Function(bool)? successHandler,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseResponseMeta,
          [
            response,
            successHandler,
          ],
        ),
        returnValue: _i20.ifNotNull(
              _i20.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #parseResponseMeta,
                  [
                    response,
                    successHandler,
                  ],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_4<T>(
              this,
              Invocation.method(
                #parseResponseMeta,
                [
                  response,
                  successHandler,
                ],
              ),
            ),
      ) as _i5.Future<T>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i10.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i5.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i6.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.IOSOptions get iOptions => (super.noSuchMethod(
        Invocation.getter(#iOptions),
        returnValue: _FakeIOSOptions_5(
          this,
          Invocation.getter(#iOptions),
        ),
      ) as _i6.IOSOptions);

  @override
  _i6.AndroidOptions get aOptions => (super.noSuchMethod(
        Invocation.getter(#aOptions),
        returnValue: _FakeAndroidOptions_6(
          this,
          Invocation.getter(#aOptions),
        ),
      ) as _i6.AndroidOptions);

  @override
  _i6.LinuxOptions get lOptions => (super.noSuchMethod(
        Invocation.getter(#lOptions),
        returnValue: _FakeLinuxOptions_7(
          this,
          Invocation.getter(#lOptions),
        ),
      ) as _i6.LinuxOptions);

  @override
  _i6.WindowsOptions get wOptions => (super.noSuchMethod(
        Invocation.getter(#wOptions),
        returnValue: _FakeWindowsOptions_8(
          this,
          Invocation.getter(#wOptions),
        ),
      ) as _i6.WindowsOptions);

  @override
  _i6.WebOptions get webOptions => (super.noSuchMethod(
        Invocation.getter(#webOptions),
        returnValue: _FakeWebOptions_9(
          this,
          Invocation.getter(#webOptions),
        ),
      ) as _i6.WebOptions);

  @override
  _i6.MacOsOptions get mOptions => (super.noSuchMethod(
        Invocation.getter(#mOptions),
        returnValue: _FakeMacOsOptions_10(
          this,
          Invocation.getter(#mOptions),
        ),
      ) as _i6.MacOsOptions);

  @override
  _i5.Future<void> write({
    required String? key,
    required String? value,
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> read({
    required String? key,
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> containsKey({
    required String? key,
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> delete({
    required String? key,
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, String>> readAll({
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i5.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<void> deleteAll({
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [InvoiceRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvoiceRemoteDataSource extends _i1.Mock
    implements _i21.InvoiceRemoteDataSource {
  MockInvoiceRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i22.InvoicesResponseData>> getDataInvoices(
    String? type,
    int? offset,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDataInvoices,
          [
            type,
            offset,
            limit,
          ],
        ),
        returnValue: _i5.Future<List<_i22.InvoicesResponseData>>.value(
            <_i22.InvoicesResponseData>[]),
      ) as _i5.Future<List<_i22.InvoicesResponseData>>);

  @override
  _i5.Future<_i7.InvoiceDetailResponse> getInvoiceDetail(String? invoiceCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoiceDetail,
          [invoiceCode],
        ),
        returnValue: _i5.Future<_i7.InvoiceDetailResponse>.value(
            _FakeInvoiceDetailResponse_11(
          this,
          Invocation.method(
            #getInvoiceDetail,
            [invoiceCode],
          ),
        )),
      ) as _i5.Future<_i7.InvoiceDetailResponse>);

  @override
  _i5.Future<_i23.Uint8List> downLoadInvoice(String? invoiceCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #downLoadInvoice,
          [invoiceCode],
        ),
        returnValue: _i5.Future<_i23.Uint8List>.value(_i23.Uint8List(0)),
      ) as _i5.Future<_i23.Uint8List>);

  @override
  _i5.Future<_i7.CheckEvaluationResponse> checkTalentEvaluation(
          String? invoiceCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkTalentEvaluation,
          [invoiceCode],
        ),
        returnValue: _i5.Future<_i7.CheckEvaluationResponse>.value(
            _FakeCheckEvaluationResponse_12(
          this,
          Invocation.method(
            #checkTalentEvaluation,
            [invoiceCode],
          ),
        )),
      ) as _i5.Future<_i7.CheckEvaluationResponse>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i24.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i8.CheckEmailResponse> checkEmailLogin(
    String? email, {
    String? recaptchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkEmailLogin,
          [email],
          {#recaptchaToken: recaptchaToken},
        ),
        returnValue:
            _i5.Future<_i8.CheckEmailResponse>.value(_FakeCheckEmailResponse_13(
          this,
          Invocation.method(
            #checkEmailLogin,
            [email],
            {#recaptchaToken: recaptchaToken},
          ),
        )),
      ) as _i5.Future<_i8.CheckEmailResponse>);

  @override
  _i5.Future<_i9.LoginResponse> doLogin(
    String? username,
    String? password, {
    String? recaptchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #doLogin,
          [
            username,
            password,
          ],
          {#recaptchaToken: recaptchaToken},
        ),
        returnValue: _i5.Future<_i9.LoginResponse>.value(_FakeLoginResponse_14(
          this,
          Invocation.method(
            #doLogin,
            [
              username,
              password,
            ],
            {#recaptchaToken: recaptchaToken},
          ),
        )),
      ) as _i5.Future<_i9.LoginResponse>);

  @override
  _i5.Future<bool> doLogout() => (super.noSuchMethod(
        Invocation.method(
          #doLogout,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> sendForgotPassword(
    String? email, {
    String? recaptchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendForgotPassword,
          [email],
          {#recaptchaToken: recaptchaToken},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> changePassword(
    String? oldPass,
    String? newPass,
    String? confirmPass,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            oldPass,
            newPass,
            confirmPass,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> resendVerification(
    String? email,
    String? productName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendVerification,
          [
            email,
            productName,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [SharedPref].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPref extends _i1.Mock implements _i2.SharedPref {
  MockSharedPref() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i10.SharedPreferences> get sharedPreferences =>
      (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue:
            _i5.Future<_i10.SharedPreferences>.value(_FakeSharedPreferences_15(
          this,
          Invocation.getter(#sharedPreferences),
        )),
      ) as _i5.Future<_i10.SharedPreferences>);

  @override
  _i11.SecureStorageService get secureStorage => (super.noSuchMethod(
        Invocation.getter(#secureStorage),
        returnValue: _FakeSecureStorageService_16(
          this,
          Invocation.getter(#secureStorage),
        ),
      ) as _i11.SecureStorageService);

  @override
  _i5.Future<void> saveUserAndToken(_i9.LoginResponse? userAndToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserAndToken,
          [userAndToken],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveTokens({
    required String? accessToken,
    required String? refreshToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> saveTime(String? time) => (super.noSuchMethod(
        Invocation.method(
          #saveTime,
          [time],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteTime() => (super.noSuchMethod(
        Invocation.method(
          #deleteTime,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i12.ForgetPinResponse> getTime() => (super.noSuchMethod(
        Invocation.method(
          #getTime,
          [],
        ),
        returnValue:
            _i5.Future<_i12.ForgetPinResponse>.value(_FakeForgetPinResponse_17(
          this,
          Invocation.method(
            #getTime,
            [],
          ),
        )),
      ) as _i5.Future<_i12.ForgetPinResponse>);

  @override
  _i5.Future<void> saveFcmToken(String? fcmToken) => (super.noSuchMethod(
        Invocation.method(
          #saveFcmToken,
          [fcmToken],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getFcmToken() => (super.noSuchMethod(
        Invocation.method(
          #getFcmToken,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i20.dummyValue<String>(
          this,
          Invocation.method(
            #getFcmToken,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> saveRemoteVersion(String? remote) => (super.noSuchMethod(
        Invocation.method(
          #saveRemoteVersion,
          [remote],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getRemoteVersion() => (super.noSuchMethod(
        Invocation.method(
          #getRemoteVersion,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i20.dummyValue<String>(
          this,
          Invocation.method(
            #getRemoteVersion,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> saveTalents(List<_i25.TalentsSelectedData>? talents) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTalents,
          [talents],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i25.TalentsSelectedData>> getTalents() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTalents,
          [],
        ),
        returnValue: _i5.Future<List<_i25.TalentsSelectedData>>.value(
            <_i25.TalentsSelectedData>[]),
      ) as _i5.Future<List<_i25.TalentsSelectedData>>);

  @override
  _i5.Future<bool> updateReasonByJobAssigneeId(
    int? jobAssigneeId,
    String? newReason,
    bool? isSelected,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReasonByJobAssigneeId,
          [
            jobAssigneeId,
            newReason,
            isSelected,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> clearTalents() => (super.noSuchMethod(
        Invocation.method(
          #clearTalents,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveProfileData(_i26.ProfileResponse? profileData) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProfileData,
          [profileData],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i26.ProfileResponse?> getProfileResponse() => (super.noSuchMethod(
        Invocation.method(
          #getProfileResponse,
          [],
        ),
        returnValue: _i5.Future<_i26.ProfileResponse?>.value(),
      ) as _i5.Future<_i26.ProfileResponse?>);

  @override
  _i5.Future<void> removeDataPref() => (super.noSuchMethod(
        Invocation.method(
          #removeDataPref,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [InvoiceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvoiceRepository extends _i1.Mock implements _i27.InvoiceRepository {
  MockInvoiceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<
      _i13.Either<_i28.Failure, List<_i29.InvoicesDataModel>>> getInvoices(
    String? type,
    int? offset,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoices,
          [
            type,
            offset,
            limit,
          ],
        ),
        returnValue: _i5.Future<
                _i13.Either<_i28.Failure, List<_i29.InvoicesDataModel>>>.value(
            _FakeEither_18<_i28.Failure, List<_i29.InvoicesDataModel>>(
          this,
          Invocation.method(
            #getInvoices,
            [
              type,
              offset,
              limit,
            ],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, List<_i29.InvoicesDataModel>>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, _i30.InvoiceDetailModel>>
      getInvoiceDetail(String? invoiceCode) => (super.noSuchMethod(
            Invocation.method(
              #getInvoiceDetail,
              [invoiceCode],
            ),
            returnValue: _i5.Future<
                    _i13.Either<_i28.Failure, _i30.InvoiceDetailModel>>.value(
                _FakeEither_18<_i28.Failure, _i30.InvoiceDetailModel>(
              this,
              Invocation.method(
                #getInvoiceDetail,
                [invoiceCode],
              ),
            )),
          ) as _i5.Future<_i13.Either<_i28.Failure, _i30.InvoiceDetailModel>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, _i23.Uint8List>> downloadInvoice(
          String? invoiceCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadInvoice,
          [invoiceCode],
        ),
        returnValue:
            _i5.Future<_i13.Either<_i28.Failure, _i23.Uint8List>>.value(
                _FakeEither_18<_i28.Failure, _i23.Uint8List>(
          this,
          Invocation.method(
            #downloadInvoice,
            [invoiceCode],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, _i23.Uint8List>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, _i7.CheckEvaluationResponse>>
      checkTalentsEvaluation(String? id) => (super.noSuchMethod(
            Invocation.method(
              #checkTalentsEvaluation,
              [id],
            ),
            returnValue: _i5.Future<
                    _i13
                    .Either<_i28.Failure, _i7.CheckEvaluationResponse>>.value(
                _FakeEither_18<_i28.Failure, _i7.CheckEvaluationResponse>(
              this,
              Invocation.method(
                #checkTalentsEvaluation,
                [id],
              ),
            )),
          ) as _i5
              .Future<_i13.Either<_i28.Failure, _i7.CheckEvaluationResponse>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i15.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i13.Either<_i28.Failure, _i31.CheckEmailModel>> checkEmailLogin(
    String? email, {
    String? recaptchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkEmailLogin,
          [email],
          {#recaptchaToken: recaptchaToken},
        ),
        returnValue:
            _i5.Future<_i13.Either<_i28.Failure, _i31.CheckEmailModel>>.value(
                _FakeEither_18<_i28.Failure, _i31.CheckEmailModel>(
          this,
          Invocation.method(
            #checkEmailLogin,
            [email],
            {#recaptchaToken: recaptchaToken},
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, _i31.CheckEmailModel>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, _i32.LoginModel>> doLogin(
    String? username,
    String? password, {
    String? recaptchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #doLogin,
          [
            username,
            password,
          ],
          {#recaptchaToken: recaptchaToken},
        ),
        returnValue:
            _i5.Future<_i13.Either<_i28.Failure, _i32.LoginModel>>.value(
                _FakeEither_18<_i28.Failure, _i32.LoginModel>(
          this,
          Invocation.method(
            #doLogin,
            [
              username,
              password,
            ],
            {#recaptchaToken: recaptchaToken},
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, _i32.LoginModel>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, bool>> getAuthState() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthState,
          [],
        ),
        returnValue: _i5.Future<_i13.Either<_i28.Failure, bool>>.value(
            _FakeEither_18<_i28.Failure, bool>(
          this,
          Invocation.method(
            #getAuthState,
            [],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, bool>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, bool>> doLogout() => (super.noSuchMethod(
        Invocation.method(
          #doLogout,
          [],
        ),
        returnValue: _i5.Future<_i13.Either<_i28.Failure, bool>>.value(
            _FakeEither_18<_i28.Failure, bool>(
          this,
          Invocation.method(
            #doLogout,
            [],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, bool>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, bool>> sendForgotPass(
    String? email, {
    String? recaptchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendForgotPass,
          [email],
          {#recaptchaToken: recaptchaToken},
        ),
        returnValue: _i5.Future<_i13.Either<_i28.Failure, bool>>.value(
            _FakeEither_18<_i28.Failure, bool>(
          this,
          Invocation.method(
            #sendForgotPass,
            [email],
            {#recaptchaToken: recaptchaToken},
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, bool>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, bool>> changePassword(
    String? oldPass,
    String? newPass,
    String? confirmPass,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            oldPass,
            newPass,
            confirmPass,
          ],
        ),
        returnValue: _i5.Future<_i13.Either<_i28.Failure, bool>>.value(
            _FakeEither_18<_i28.Failure, bool>(
          this,
          Invocation.method(
            #changePassword,
            [
              oldPass,
              newPass,
              confirmPass,
            ],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, bool>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, bool>> resendVerification(
    String? email,
    String? productName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendVerification,
          [
            email,
            productName,
          ],
        ),
        returnValue: _i5.Future<_i13.Either<_i28.Failure, bool>>.value(
            _FakeEither_18<_i28.Failure, bool>(
          this,
          Invocation.method(
            #resendVerification,
            [
              email,
              productName,
            ],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, bool>>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i33.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i13.Either<_i28.Failure, _i34.ProfileModel>> getProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue:
            _i5.Future<_i13.Either<_i28.Failure, _i34.ProfileModel>>.value(
                _FakeEither_18<_i28.Failure, _i34.ProfileModel>(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, _i34.ProfileModel>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, _i34.ProfileModel>> getProfileLocal() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileLocal,
          [],
        ),
        returnValue:
            _i5.Future<_i13.Either<_i28.Failure, _i34.ProfileModel>>.value(
                _FakeEither_18<_i28.Failure, _i34.ProfileModel>(
          this,
          Invocation.method(
            #getProfileLocal,
            [],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, _i34.ProfileModel>>);
}

/// A class which mocks [AttendanceRepostiory].
///
/// See the documentation for Mockito's code generation for more information.
class MockAttendanceRepostiory extends _i1.Mock
    implements _i35.AttendanceRepostiory {
  MockAttendanceRepostiory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<
      _i13.Either<_i28.Failure, List<_i36.AttendanceModel>>> getAttendance(
    int? offset,
    int? limit,
    String? name,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAttendance,
          [
            offset,
            limit,
            name,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i5.Future<
                _i13.Either<_i28.Failure, List<_i36.AttendanceModel>>>.value(
            _FakeEither_18<_i28.Failure, List<_i36.AttendanceModel>>(
          this,
          Invocation.method(
            #getAttendance,
            [
              offset,
              limit,
              name,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, List<_i36.AttendanceModel>>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, List<_i36.AttendanceFailModel>>>
      getAttendanceFail(
    int? offset,
    int? limit,
    String? name,
    String? startDate,
    String? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAttendanceFail,
              [
                offset,
                limit,
                name,
                startDate,
                endDate,
              ],
            ),
            returnValue: _i5.Future<
                    _i13.Either<_i28.Failure,
                        List<_i36.AttendanceFailModel>>>.value(
                _FakeEither_18<_i28.Failure, List<_i36.AttendanceFailModel>>(
              this,
              Invocation.method(
                #getAttendanceFail,
                [
                  offset,
                  limit,
                  name,
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i5.Future<
              _i13.Either<_i28.Failure, List<_i36.AttendanceFailModel>>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, List<_i36.AttendanceAbsenceModel>>>
      getAttendanceAbsense(
    String? name,
    String? startDate,
    String? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAttendanceAbsense,
              [
                name,
                startDate,
                endDate,
              ],
            ),
            returnValue: _i5.Future<
                    _i13.Either<_i28.Failure,
                        List<_i36.AttendanceAbsenceModel>>>.value(
                _FakeEither_18<_i28.Failure, List<_i36.AttendanceAbsenceModel>>(
              this,
              Invocation.method(
                #getAttendanceAbsense,
                [
                  name,
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i5.Future<
              _i13.Either<_i28.Failure, List<_i36.AttendanceAbsenceModel>>>);

  @override
  _i5.Future<_i13.Either<_i28.Failure, _i23.Uint8List>> downloadAttendance(
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadAttendance,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i5.Future<_i13.Either<_i28.Failure, _i23.Uint8List>>.value(
                _FakeEither_18<_i28.Failure, _i23.Uint8List>(
          this,
          Invocation.method(
            #downloadAttendance,
            [
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, _i23.Uint8List>>);
}

/// A class which mocks [AuthenticationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationManager extends _i1.Mock
    implements _i17.AuthenticationManager {
  MockAuthenticationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPref get sharedPref => (super.noSuchMethod(
        Invocation.getter(#sharedPref),
        returnValue: _FakeSharedPref_0(
          this,
          Invocation.getter(#sharedPref),
        ),
      ) as _i2.SharedPref);

  @override
  _i14.AuthStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i14.AuthStatus.initial,
      ) as _i14.AuthStatus);

  @override
  _i14.AuthState get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: _FakeAuthState_19(
          this,
          Invocation.getter(#value),
        ),
      ) as _i14.AuthState);

  @override
  set value(_i14.AuthState? newValue) => super.noSuchMethod(
        Invocation.setter(
          #value,
          newValue,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> checkLoginStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkLoginStatus,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> login(_i32.UserLoginModel? newUser) => (super.noSuchMethod(
        Invocation.method(
          #login,
          [newUser],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i37.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i37.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DoLoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoLoginUseCase extends _i1.Mock implements _i38.DoLoginUseCase {
  MockDoLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_20(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i15.AuthRepository);

  @override
  _i16.GetProfileUseCase get getProfileUseCase => (super.noSuchMethod(
        Invocation.getter(#getProfileUseCase),
        returnValue: _FakeGetProfileUseCase_21(
          this,
          Invocation.getter(#getProfileUseCase),
        ),
      ) as _i16.GetProfileUseCase);

  @override
  _i17.AuthenticationManager get authenticationManager => (super.noSuchMethod(
        Invocation.getter(#authenticationManager),
        returnValue: _FakeAuthenticationManager_22(
          this,
          Invocation.getter(#authenticationManager),
        ),
      ) as _i17.AuthenticationManager);

  @override
  _i5.Future<_i13.Either<_i28.Failure, _i32.LoginModel>> execute(
    String? username,
    String? password, {
    String? recaptchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            username,
            password,
          ],
          {#recaptchaToken: recaptchaToken},
        ),
        returnValue:
            _i5.Future<_i13.Either<_i28.Failure, _i32.LoginModel>>.value(
                _FakeEither_18<_i28.Failure, _i32.LoginModel>(
          this,
          Invocation.method(
            #execute,
            [
              username,
              password,
            ],
            {#recaptchaToken: recaptchaToken},
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, _i32.LoginModel>>);
}

/// A class which mocks [DoLogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoLogoutUseCase extends _i1.Mock implements _i39.DoLogoutUseCase {
  MockDoLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_20(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i15.AuthRepository);

  @override
  _i17.AuthenticationManager get authenticationManager => (super.noSuchMethod(
        Invocation.getter(#authenticationManager),
        returnValue: _FakeAuthenticationManager_22(
          this,
          Invocation.getter(#authenticationManager),
        ),
      ) as _i17.AuthenticationManager);

  @override
  _i5.Future<_i13.Either<_i28.Failure, bool>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i5.Future<_i13.Either<_i28.Failure, bool>>.value(
            _FakeEither_18<_i28.Failure, bool>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, bool>>);
}

/// A class which mocks [SendForgotPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendForgotPasswordUseCase extends _i1.Mock
    implements _i40.SendForgotPasswordUseCase {
  MockSendForgotPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_20(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i15.AuthRepository);

  @override
  _i5.Future<_i13.Either<_i28.Failure, bool>> execute(
    String? email, {
    String? recaptchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [email],
          {#recaptchaToken: recaptchaToken},
        ),
        returnValue: _i5.Future<_i13.Either<_i28.Failure, bool>>.value(
            _FakeEither_18<_i28.Failure, bool>(
          this,
          Invocation.method(
            #execute,
            [email],
            {#recaptchaToken: recaptchaToken},
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, bool>>);
}

/// A class which mocks [ChangePasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangePasswordUseCase extends _i1.Mock
    implements _i41.ChangePasswordUseCase {
  MockChangePasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_20(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i15.AuthRepository);

  @override
  _i5.Future<_i13.Either<_i28.Failure, bool>> execute(
    String? oldPass,
    String? newPass,
    String? confirmPass,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            oldPass,
            newPass,
            confirmPass,
          ],
        ),
        returnValue: _i5.Future<_i13.Either<_i28.Failure, bool>>.value(
            _FakeEither_18<_i28.Failure, bool>(
          this,
          Invocation.method(
            #execute,
            [
              oldPass,
              newPass,
              confirmPass,
            ],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, bool>>);
}

/// A class which mocks [GetProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileUseCase extends _i1.Mock implements _i16.GetProfileUseCase {
  MockGetProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i13.Either<_i28.Failure, _i34.ProfileModel>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i5.Future<_i13.Either<_i28.Failure, _i34.ProfileModel>>.value(
                _FakeEither_18<_i28.Failure, _i34.ProfileModel>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i13.Either<_i28.Failure, _i34.ProfileModel>>);
}

/// A class which mocks [RecaptchaUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecaptchaUseCase extends _i1.Mock implements _i42.RecaptchaUseCase {
  MockRecaptchaUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initializeClient() => (super.noSuchMethod(
        Invocation.method(
          #initializeClient,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getToken(_i43.RecaptchaAction? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [action],
        ),
        returnValue: _i5.Future<String>.value(_i20.dummyValue<String>(
          this,
          Invocation.method(
            #getToken,
            [action],
          ),
        )),
      ) as _i5.Future<String>);
}
